### ISSUE TITLE
set up a demo of echis - khis integration (test environment) for UAT

### ISSUE THREAD

**Issue by kitsao** [moh-kenya/echis-2.0-integration#106]
1. For echis, use the training instance: [chis-training.health.go.ke](https://chis-training.health.go.ke/)
2. For khis, use the test environment: [test.hiskenya.org](https://test.hiskenya.org/)
3. For the mediator, use the staging environment version

To be done by Monday **August 10, 2023**

**Comment by derickl** [comment]
The due date on this issue is stale. Do you want to revise it @kitsao ?

**Comment by kitsao** [comment]
Dates revised @derickl.

**Comment by kitsao** [comment]
This will be done in the November sprint, finally.

**Comment by derickl** [comment]
Marking this as complete
