### ISSUE TITLE
Flag mismatching client details on eCHIS for CHP Follow up

### ISSUE THREAD

**Issue by freddieptf** [moh-kenya/echis-2.0-integration#117]
> Upon submitting the same national ID with different names, the two clients get the same UPI. Ensure that the mismatching details are flagged for the CHP to follow up instead of updating with the UPI.

Issue from https://github.com/moh-kenya/config-echis-2.0/issues/1353

**Comment by freddieptf** [comment]
From our last discussion, we had talked about creating a report detailing what fields are wrong and then using a task on eCHIS to notify the CHP for follow up @karimkkanji @kitsao. Is this still the preferred approach?

**Comment by karimkkanji** [comment]
@freddieptf This is key:
https://github.com/moh-kenya/echis-2.0-integration/pull/118#issuecomment-1750398991

**Comment by karimkkanji** [comment]
If a user was registered on an EMR, then they use a different number from
the one they used in the EMR, it is not assigning the UPI. Users may decide
to give a different phone number and it is still okay. Using one that is
different from CR is allowed but in this case it fails.

**Comment by karimkkanji** [comment]
> @freddieptf This is key:
> 
> https://github.com/moh-kenya/echis-2.0-integration/pull/118#issuecomment-1750398991

In this screenshot, the upi is not stored as it says phone number is mismatched. This is on the mediator implementation.

**Comment by freddieptf** [comment]
Thanks for pointing that out @karimkkanji, create a ticket and we can work on a fix for that
