### ISSUE TITLE
eCHIS => Afya Ke: add json form to be used for inbound acknowledgements for CHV tasking

### ISSUE THREAD

**Issue by deemixsouth** [moh-kenya/echis-2.0-integration#37]
Details we expect from AfyaKE are as follow

| AfyaKE payload attribute | Description |
| ------------- | ------------- |
| subject | Patient Details (UPI) |
| authoredOn | date service offered |
| authoredOn | Date of visit |
| notes | Follow up instructions |
| notes | Health Facility Contact |

#### To Do

1. Create JSON form in [config echis settings](https://github.com/moh-kenya/config-echis-2.0/blob/main/app_settings/forms.json) to handle the contain the data above. Use this [snippet](https://github.com/medic/interoperability/blob/a386a6918fbb0f0248b8085164cae91e81e8349e/cht-config/app_settings.json#L523) and [documentation](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/forms/) for reference.
2. Refactor the [referrals controller](https://github.com/moh-kenya/echis-2.0-integration/blob/4b440b98293f5a7fe7a1034c0b27da4d7595e44e/src/controllers/referral.js#L49) to send the data above (from Afya KE) to match your form above.

**Comment by billwambua** [comment]
@kitsao the field names `authoredOn` and `notes` are repeated but with different meanings.

Do clarify that.

**Comment by billwambua** [comment]
This was resolved.

Closing.
