### ISSUE TITLE
khis: host couch2pg service to continuously stream data from couchdb to postgres database

### ISSUE THREAD

**Issue by kitsao** [moh-kenya/echis-2.0-integration#9]
Ezra to assist.

**Comment by deemixsouth** [comment]
Tasked Completed .
@kitsao you can confirm, then we can close this ticket

**Comment by kitsao** [comment]
@deemixsouth we close when changes from [config-echis-2.0/pull/783](https://github.com/moh-kenya/config-echis-2.0/pull/783) are executed. cc @liveBuildKenya

**Comment by kitsao** [comment]
Done.
